name: CI

on:
  push:
  schedule:
    - cron: '10 1 * * *'

jobs:
  build:
    name: Generate new plot html
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create folders
      run: mkdir -p raw output
    - name: Cache wanikani data
      id: cache
      uses: actions/cache@v1
      with:
        path: raw
        key: ${{ runner.os }}-wk
    - name: Get data from wanikani
      run: ./get.sh
    - name: Transcribe data
      run: python transcribe.py
    - name: Generate html
      run: python generateHtml.py
    - name: Create html artifact
      uses: actions/upload-artifact@v1
      with:
        name: plot
        path: output/index.html

  publish:
    name: Publish html to github.io page
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: plot
        path: index.html
    - name: Commit to remote repo
      run: |
        git clone -n https://github.com/zorfmorf/zorfmorf.github.io.git --depth 1
        cd zorfmorf.github.io
        git checkout HEAD index.html
        mv ../index.html index.html
        git config --local user.email "spam@aborium.de"
        git config --local user.name "GitHub Action"
        git add index.html
        git commit -m "Update plot to latest version"
        git push
