name: CI

on:
  push:
  schedule:
    - cron: '10 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create folders
      run: mkdir -p raw output
    - name: Cache wanikani data
      id: cache
      uses: actions/cache@v1
      with:
        path: raw
        key: ${{ runner.os }}-wk
    - name: Get data from wanikani
      run: ./get.sh
    - name: Transcribe data
      run: python transcribe.py
    - name: Generate html
      run: python generateHtml.py
    - name: Create html artifact
      uses: actions/upload-artifact@v1
      with:
        name: plot
        path: output/index.html
