name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: plot
        path: index.html
    - name: Commit to remote repo
      run: |
        git clone -n git@github.com:zorfmorf/zorfmorf.github.io.git --depth 1
        cd zorfmorf.github.io
        git checkout HEAD index.html
        mv ../index.html index.html
        git add index.html
        git commit -m "Update plot to latest version"
